// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.DB;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109085700_AddMonstersToTable")]
    partial class AddMonstersToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterId"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("int");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            ArmorClass = 15,
                            AttackModifier = 40,
                            AttackPerRound = 1,
                            Damage = "8d10",
                            DamageModifier = 4,
                            HitPoints = 84,
                            Name = "Troll"
                        },
                        new
                        {
                            MonsterId = 2,
                            ArmorClass = 17,
                            AttackModifier = 10,
                            AttackPerRound = 1,
                            Damage = "5d8",
                            DamageModifier = 3,
                            HitPoints = 32,
                            Name = "Bronze Dragon Wyrmling"
                        },
                        new
                        {
                            MonsterId = 3,
                            ArmorClass = 15,
                            AttackModifier = 24,
                            AttackPerRound = 1,
                            Damage = "12d10",
                            DamageModifier = 4,
                            HitPoints = 90,
                            Name = "Salamander"
                        },
                        new
                        {
                            MonsterId = 4,
                            ArmorClass = 11,
                            AttackModifier = 12,
                            AttackPerRound = 1,
                            Damage = "4d10",
                            DamageModifier = 4,
                            HitPoints = 34,
                            Name = "Brown Bear"
                        },
                        new
                        {
                            MonsterId = 5,
                            ArmorClass = 12,
                            AttackModifier = 1,
                            AttackPerRound = 1,
                            Damage = "1d4",
                            DamageModifier = 1,
                            HitPoints = 12,
                            Name = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
